LemonScone/pixel-art

backend/package-lock.json
backend/package.json
backend/src/app.controller.ts
backend/src/main.ts
backend/src/utils/swagger.ts

swagger 설치 및 적용하였습니다.
​
​
resolve #5
​
​
​

[Feat] swagger 설치 및 적용

---

frontend/.eslintrc.cjs
frontend/.gitignore
frontend/index.html
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/main.tsx
frontend/src/vite-env.d.ts
frontend/tsconfig.json
frontend/tsconfig.node.json
frontend/vite.config.ts

​frontend 디렉토리에 react를 설치했습니다.
​
resolve #8
​
​
​

[Feature] 리액트 프로젝트 초기화

---

.github/workflows/deploy.yml

​github action 추가
​
resolve #7
​
​
​

[Feature] 배포를 위한 Github Action 추가

---

backend/src/main.ts
backend/src/utils/httpExceptionFilter.ts

httpException을 공통으로 처리하는 exception filter 적용했어용
​
​
resolve #14
​
​
​

[Feature] exception filter 추가 및 전역 적용

---

backend/src/app.module.ts
backend/src/artworks/artworks.controller.spec.ts
backend/src/artworks/artworks.controller.ts
backend/src/artworks/artworks.module.ts
backend/src/artworks/artworks.service.spec.ts
backend/src/artworks/artworks.service.ts

* Feat: projects 관련 API 생성
* Fix: #17 리뷰 반영 - insertId 처리, transaction 처리, frame 조회
* Feat: #17 리뷰 반영 - 사용자별 projects 조회 API 생성
* Feat: #17 리뷰 반영 - 주석 제거
* Feat: artworks 관련 API 생성

[Deploy] artworks 관련 API 생성 (#21)

---

backend/src/auth/guards/jwt.guard.ts
backend/src/projects/dto/create-project-dto.ts
backend/src/projects/dto/update-project-dto.ts
backend/src/projects/projects.controller.ts
backend/src/projects/projects.module.ts
backend/src/projects/projects.service.ts

[Enhance] projects 관련 API 개선

---

frontend/package-lock.json
frontend/package.json
frontend/postcss.config.js
frontend/src/App.tsx
frontend/src/index.css
frontend/tailwind.config.js

tailwindcss를 설치하고 적용했습니다.
​
​
resolve #27 
​
​
​

[Feature] tailwindcss 설치 및 적용

---

frontend/src/components/Pixel.tsx
frontend/src/components/PixelContainer.tsx
frontend/src/constants/index.ts
frontend/src/utils/color.ts
frontend/src/utils/grid.ts
frontend/tests/utils/getGridBackgroundIndex.test.ts

- background를 체크 무늬로 변경했습니다.
- 체크 무늬는 추가한 `getGridBackgroundIndex` 함수로 결정됩니다. 반환값이 `0`이면 `#d9d9d9` 색상, `1`이면 `#ffffff` 입니다.
- 그림 도구로 변경된 색상은 `style` property의 `background-color`로 지정됩니다. 
- hover 시 도구 사이즈에 맞게 표시됩니다.
- `Pixel` 컴포넌트에 `onPointerEnter`와 `onPointerLeave`가 추가되었습다. `pointerEnter`, `pointerLeave` 이벤트 발생시 상위 컴포넌트로 `id`를 전달합니다.
```ts
const handlePointerEnter = (id: number) => {
if (ref.current) {
// 전달된 `id`는 색을 칠하는 것과 마찬가지로 사이즈에 맞춰 함께 적용되어야 할 index를 `getTargetIndexes` 함수로 받아옵니다. 
const indexes = getTargetIndexes(
id,
toolOptions[selectedTool].size,
columns,
rows
);
// `useRef`를 사용해 하위 `.pixel` 요소들을 가져와 인덱스에 해당하는 pixel의 색상을 변경합니다.
const pixels = ref.current.querySelectorAll<HTMLDivElement>(".pixel");
indexes.forEach(index => {
// `grid[index]`에 색상이 있다면 색칠된 pixel이고 아니라면 빈 pixel입니다. …
```

[Enhance] pixel hover 개선

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Navbar.tsx
frontend/src/main.tsx
frontend/src/pages/Editor.tsx
frontend/src/pages/Error.tsx
frontend/src/pages/Gallery.tsx
frontend/src/pages/Root.tsx
frontend/src/pages/SignIn.tsx
frontend/src/pages/index.ts
frontend/src/routes/AppRoutes.tsx

react-router-dom 설치 후 ​router를 설정했습니다.
`src/pages/Root.tsx`
화면 전체를 감싸는 컴포넌트입니다. `<Outlet />`자리에 `children` routes가 들어갑니다.
`/`
`src/pages/Editor.tsx`
`/gallery`
`src/pages/Gallery.tsx`
`/login`
`src/pages/SignIn.tsx`
error page
`src/pages/Error.tsx`
​
resolve #46
​
​
​

[Feature] router 설정

---

frontend/package.json
frontend/src/routes/AppRoutes.tsx

* Feat: lazy loading 추가
* Feat: build 스크립트에 tsc 제외

[Deploy] code splitting 추가 (#64)

---

.github/workflows/deploy_backend.yml
.github/workflows/deploy_frontend.yml
backend/src/utils/httpExceptionFilter.ts

* Feat: github action workflows 수정 (backend/frontend 분리)
* Fix: exception 없는 경우 처리

[Deploy] github action workflows 수정 (#67)

---

.github/workflows/deploy_backend.yml
.github/workflows/deploy_frontend.yml
frontend/src/pages/Gallery.tsx

[Deploy] github actions workflows paths 수정

---

.github/workflows/deploy_frontend.yml
frontend/src/pages/Gallery.tsx

[Deploy] github actions workflows target 옵션 수정

---

.github/workflows/deploy_backend.yml
backend/.gitignore
backend/package.json
backend/src/app.module.ts
backend/src/envs/helper/env.helper.ts
backend/src/main.ts

* Fix: backend deploy workflow 수정 /backend 경로에서 서버 시작
* Fix: 서버 실행 스크립트를 환경 변수 구분해서 실행
* Fix: env 파일 무시
* Feat: env 파일 환경에 따라 불러오기
* Feat: swagger는 development일 때 적용, https는 production일 때 적용

[Feature] SSL 적용 (#83)

---

backend/src/auth/auth.controller.ts
backend/src/auth/auth.service.ts
backend/src/auth/dto/auth-login-response.dto.ts
backend/src/projects/projects.controller.ts
backend/src/projects/projects.service.ts
frontend/package-lock.json
frontend/package.json
frontend/src/components/Navbar.test.tsx
frontend/src/components/Navbar.tsx
frontend/src/components/SignIn/SignInForm.tsx
frontend/src/hooks/useAuth.ts
frontend/src/main.tsx
frontend/src/pages/Editor.tsx
frontend/src/store/apis/authApi.ts
frontend/src/store/apis/projectsApi.ts
frontend/src/store/index.ts
frontend/src/store/slices/authSlice.ts
frontend/src/tests/mocks/handlers.ts
frontend/src/tests/setup.ts
frontend/src/types/Auth.ts

data fetching에 redux-toolkit query 적용 및 그에 따른 테스트 수정
​
​
resolve #87
​
​
​

[Feature] redux toolkit query 추가

---

backend/src/projects/projects.controller.ts
backend/src/projects/projects.service.ts
frontend/src/components/NewProject.tsx
frontend/src/store/index.ts
frontend/src/store/slices/projectsSlice.ts
frontend/src/tests/fixtures/projectsStore.ts

- ​New project 기능 추가
- migration시 `for...of`문 내에서 `return`코드 삭제(하나만 insert 됩니다.)
​
resolve #103
​
​
​

[Feature] New project 기능 추가

---

frontend/src/components/ResetProject.tsx
frontend/src/pages/Editor.tsx
frontend/src/store/index.ts
frontend/src/store/slices/projectsSlice.ts
frontend/tailwind.config.js

​- 현재 frame reset 기능을 추가했습니다.
​
resolve #105
​
​
​

[Feature] Reset 기능 추가 

---

backend/src/projects/dto/frame-dto.ts
frontend/package-lock.json
frontend/package.json
frontend/src/components/ColorPallete.tsx
frontend/src/components/ColorPicker.tsx
frontend/src/components/ColorSwatch.tsx
frontend/src/components/FrameList.test.tsx
frontend/src/components/FrameList.tsx
frontend/src/components/FrameListItem.tsx
frontend/src/components/LoadProject.tsx
frontend/src/components/NewProject.tsx
frontend/src/components/NumberPicker.tsx
frontend/src/components/ProjectsListItem.tsx
frontend/src/components/ResetProject.tsx
frontend/src/components/SaveProject.tsx
frontend/src/components/common/Modal.tsx
frontend/src/components/common/Toast/ToastList.tsx
frontend/src/index.css
frontend/src/pages/Editor.tsx
frontend/src/store/index.ts
frontend/src/store/slices/projectsSlice.ts
frontend/src/tests/utils/getFrameInterval.test.ts
frontend/src/types/Project.ts
frontend/src/utils/getFrameInterval.ts

- `Frame` 추가, 삭제, 복사, 선택 기능을 추가했습니다.
- `Frame` 순서 이동을 위해 dnd library를 설치 및 적용했습니다.
​
resolve #108
​
​
​

[Feature] Frame 기능 추가

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/ExportButton.tsx
frontend/src/components/ExportModal.tsx
frontend/src/components/FrameList.tsx
frontend/src/components/FrameListItem.tsx
frontend/src/components/GlobalModal.tsx
frontend/src/components/Navbar.tsx
frontend/src/components/PreviewModal.tsx
frontend/src/components/common/Tab.test.tsx
frontend/src/components/common/Tab.tsx
frontend/src/desc.d.ts
frontend/src/hooks/useHighlight.ts
frontend/src/store/slices/projectsSlice.ts
frontend/src/types/FileType.ts
frontend/src/types/Modal.ts
frontend/src/utils/cssParse.ts
frontend/src/utils/downloadFrames.ts

gif export를 위해 [`gifenc`](https://github.com/mattdesl/gifenc)라는 gif encoding library를 사용했습니다. 
- [library의 설명](https://github.com/mattdesl/gifenc#how-gif-encoding-works)에 따르면 gif encoding은 3가지 단계로 동작합니다.
1. 이미지의 픽셀 색상을 256개 색상으로 축소시킨 palette로 변환합니다. 수천 가지 색상을 256개 색상으로 줄이면서 좋은 품질의 결과물을 나타내는 것을 *quantization* 라고 합니다. (`quantize` 함수)
2. 픽셀을 살펴보고 축소된 palette를 기반으로 해당 픽셀의 색상과 가장 가까운 인덱스를 찾아서 인덱싱된 비트맵을 반환합니다. (`applyPalette` 함수)
3. 인덱싱된 비트맵과 palette를 통해 단일 프레임을 인코딩합니다. (`gif.writeFrame` 함수)
- **단 주의할 점은 gif는 1-bit transparency를 지원하기 때문에 투명하다/투명하지 않다 두 방식만 표시 가능하다는 것입니다.**
- 따라서 배경만 투명하게 처리하고 그외 alpha값이 있는 색상은 기존 색상으로 인코딩됩니다.
```ts
const getPaletteWithTransparent = (data: Uint8ClampedArray) => {
// alpha값(투명도를 위한 값)을 사용하기 위한 format
const format = "rgba4444";
// 첫번째 파라미터에 Uint8Array 또는 …
```

[Feature] export 추가 

---

frontend/src/components/ExportCSS.tsx
frontend/src/components/ExportModal.tsx
frontend/src/components/Preview.tsx
frontend/src/components/PreviewContainer.tsx
frontend/src/components/common/Toggle.test.tsx
frontend/src/components/common/Toggle.tsx
frontend/src/hooks/useHighlight.ts
frontend/tailwind.config.js

- `Export`시 화면에 보여지는 CSS 문자열을 copy하는 버튼을 추가했습니다.
- copy 버튼 `active`시 애니메이션 추가
- `animate` 여부를 toggle하는 `Toggle` component를 추가했습니다.
- Preview 화면에서 현재 활성화된 `frame`을 조회할 수 있도록 `activeFrameIndex`를 추가했습니다. 
- 컴포넌트 내부에서 해당 값을 계산할 수 있지만 추후에 `FrameListItem`에서 공통으로 사용할 수 있을 것 같아서 props로 전달할 수 있기 위해 추가했습니다.
​
resolve #120
​
​
​

[Feature] CSS copy 기능

---

frontend/src/components/ForgotPasswordForm.test.tsx
frontend/src/components/ForgotPasswordForm.tsx
frontend/src/components/ResetPasswordForm.test.tsx
frontend/src/components/ResetPasswordForm.tsx
frontend/src/components/common/FormField.tsx
frontend/src/hooks/useForgotPasswordFormValidator.ts
frontend/src/hooks/useResetPasswordFormValidator.ts
frontend/src/hooks/useSignInFormValidator.ts
frontend/src/hooks/useSignUpFormValidator.ts
frontend/src/pages/ResetPassword.tsx
frontend/src/pages/SignHelp.tsx
frontend/src/pages/SignIn.tsx
frontend/src/routes/AppRoutes.tsx
frontend/src/routes/ResetPasswordRoute/ResetPasswordRoute.tsx
frontend/src/routes/ResetPasswordRoute/index.ts
frontend/src/store/apis/authApi.ts
frontend/src/store/index.ts
frontend/src/tests/fixtures/auth.ts
frontend/src/tests/mocks/handlers.ts
frontend/src/types/FormFieldValidation.ts
frontend/src/utils/convertToCamelCase.ts
frontend/src/utils/validators.ts

​- 비밀번호 찾기 및 비밀번호 초기화 페이지 추가
- 비밀번호 초기화 페이지에서 `token`이 만료된 경우 비밀번호 찾기 페이지로 이동합니다. 
​
resolve #130
​
​
​

[Feature] 비밀번호 찾기 
